# Generated by Django 4.1.7 on 2023-03-09 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicgen', '0002_musicscorerecord_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicScoreRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicgen.musicscorerecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
